spring.application.name=Day65_20260902

# 디비 정보 등록
spring.datasource.url=jdbc:mysql://localhost:3306/social_login_db
spring.datasource.username=root
spring.datasource.password=1234


# jpa 설정 등록
spring.jpa.hibernate.ddl-auto=update

# 개발자입장 로그 확인
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# AI 설정 등록 
# 필요한거? api-key,모델설정
spring.ai.openai.api-key=${OPENAI-API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini

spring.ai.model.embedding=transformers