spring.application.name=FaceAndFate

# MySQL 데이터베이스 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/FaceAndFates
spring.datasource.username=root
spring.datasource.password=1234

# SQL 코드에 ? 값 출력
logging.level.org.hibernate.orm.jdbc.bind=trace

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

#${환경변수}
spring.ai.openai.api-key=${환경변수}
# gpt 모델 선택!
spring.ai.openai.chat.model=gpt-4o-mini

# 창의성/정확성
spring.ai.openai.chat.temperature=0.8

