spring.application.name=SocialLogin

spring.datasource.url=jdbc:mysql://localhost:3306/social_login_db
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

# application.properties을 사용하는 이유?
# 코드 자체와 “환경/설정값”을 분리하기 위해서
# 환경마다 설정값이 다르기 때문
# 코드 → 애플리케이션이 무엇을 하는지

# application.properties → 어떤 환경에서 어떻게 동작할지