spring.application.name=geminiAi
# 웹 포트가 충돌되면 여기서 설정!

# 구글재미니 사용하려면 API-KEY 서버 실행전에 등록!
# spring.ai.google.genai.api-key=
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
# 사용할 모델을 설정
# 본인 키를 사용하다가 에러가 발생하면 버전 3.1버전 
# 올리기
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

# 깃허브에 지금 수업내용을 올릴때 Api key단어들이 들어가면
# 깃허브가 자동으로 막아서 수업내용들이 안올라갈수있음
# .env 환경설정 파일 그 안에 넣어두고 gitignore파일에 자동으로 설정

# 0일 수록 가장 확률 높은 답만 선택! 창의성 낮아짐.
# 사실 기반 답변 0.0~0.3 추천
# 답변의 안정성과 일관성 다양성을 위해서 온도를 설정한다.
#  협업 권장 튜닝  0.3~0.5
spring.ai.google.genai.chat.temperature=0.5