spring:
  application:
    name: pgvector

  datasource:
    url: jdbc:postgresql://localhost:5433/hoteldb
    username: postgres
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        index-type: HNSW
    mcp:
      server:
        name: hotel-search-server
        version: 1.0.0
        protocol: STREAMABLE

